CREATE TABLE CLIENT (
    ID            NUMBER PRIMARY KEY,
    NAME          VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(150) NOT NULL,
    IS_ACTIVE     CHAR(1) DEFAULT 'Y'
);



CREATE TABLE INVOICE (
    ID              NUMBER PRIMARY KEY,
    CLIENT_ID       NUMBER NOT NULL,
    INVOICE_DATE    DATE DEFAULT SYSDATE,
    SUBTOTAL        NUMBER(12,2) NOT NULL,
    TAX_AMOUNT      NUMBER(12,2) NOT NULL,
    DISCOUNT        NUMBER(12,2) NOT NULL,
    TOTAL           NUMBER(12,2) NOT NULL,
    CONSTRAINT FK_INVOICE_CLIENT
        FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
